// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOhNwlOK2FpqesP95Re6DkAfi2QXcTExQ',
    appId: '1:111374266932:web:152900386d856822435061',
    messagingSenderId: '111374266932',
    projectId: 'todolist-9056c',
    authDomain: 'todolist-9056c.firebaseapp.com',
    storageBucket: 'todolist-9056c.appspot.com',
    measurementId: 'G-Z442E5JPY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcxapd50DelgO_0L--8bMEoS6WpZDmrsA',
    appId: '1:111374266932:android:13de55f4dd578b86435061',
    messagingSenderId: '111374266932',
    projectId: 'todolist-9056c',
    storageBucket: 'todolist-9056c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcI6aM4j12uozDF22EoGhWsxxBX3QF_ME',
    appId: '1:111374266932:ios:4c9aad79a5e16ba2435061',
    messagingSenderId: '111374266932',
    projectId: 'todolist-9056c',
    storageBucket: 'todolist-9056c.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcI6aM4j12uozDF22EoGhWsxxBX3QF_ME',
    appId: '1:111374266932:ios:b799911ab2ce0a29435061',
    messagingSenderId: '111374266932',
    projectId: 'todolist-9056c',
    storageBucket: 'todolist-9056c.appspot.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
